services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=${ENABLED_SERVICES:-s3,sqs,sns,iam,lambda,cloudformation,dynamodb}
      - DEBUG=0
      - EAGER_SERVICE_LOADING=1
    volumes:
      - localstack-data:/var/lib/localstack
  localstack-explorer:
    image: fgiova/localstack-explorer:latest
    ports:
      - "3001:3001"
    environment:
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - LOCALSTACK_REGION=eu-south-1
    depends_on:
      - localstack

volumes:
  localstack-data:
