/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SqsIndexRouteImport } from './routes/sqs/index'
import { Route as SnsIndexRouteImport } from './routes/sns/index'
import { Route as S3IndexRouteImport } from './routes/s3/index'
import { Route as IamIndexRouteImport } from './routes/iam/index'
import { Route as DynamodbIndexRouteImport } from './routes/dynamodb/index'
import { Route as CloudfrontIndexRouteImport } from './routes/cloudfront/index'
import { Route as CloudformationIndexRouteImport } from './routes/cloudformation/index'
import { Route as SqsQueueNameRouteImport } from './routes/sqs/$queueName'
import { Route as SnsTopicNameRouteImport } from './routes/sns/$topicName'
import { Route as S3BucketNameRouteImport } from './routes/s3/$bucketName'
import { Route as DynamodbTableNameRouteImport } from './routes/dynamodb/$tableName'
import { Route as CloudfrontDistributionIdRouteImport } from './routes/cloudfront/$distributionId'
import { Route as CloudformationStackNameRouteImport } from './routes/cloudformation/$stackName'
import { Route as IamUsersUserNameRouteImport } from './routes/iam/users/$userName'
import { Route as IamPoliciesPolicyArnRouteImport } from './routes/iam/policies/$policyArn'
import { Route as IamGroupsGroupNameRouteImport } from './routes/iam/groups/$groupName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SqsIndexRoute = SqsIndexRouteImport.update({
  id: '/sqs/',
  path: '/sqs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SnsIndexRoute = SnsIndexRouteImport.update({
  id: '/sns/',
  path: '/sns/',
  getParentRoute: () => rootRouteImport,
} as any)
const S3IndexRoute = S3IndexRouteImport.update({
  id: '/s3/',
  path: '/s3/',
  getParentRoute: () => rootRouteImport,
} as any)
const IamIndexRoute = IamIndexRouteImport.update({
  id: '/iam/',
  path: '/iam/',
  getParentRoute: () => rootRouteImport,
} as any)
const DynamodbIndexRoute = DynamodbIndexRouteImport.update({
  id: '/dynamodb/',
  path: '/dynamodb/',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudfrontIndexRoute = CloudfrontIndexRouteImport.update({
  id: '/cloudfront/',
  path: '/cloudfront/',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudformationIndexRoute = CloudformationIndexRouteImport.update({
  id: '/cloudformation/',
  path: '/cloudformation/',
  getParentRoute: () => rootRouteImport,
} as any)
const SqsQueueNameRoute = SqsQueueNameRouteImport.update({
  id: '/sqs/$queueName',
  path: '/sqs/$queueName',
  getParentRoute: () => rootRouteImport,
} as any)
const SnsTopicNameRoute = SnsTopicNameRouteImport.update({
  id: '/sns/$topicName',
  path: '/sns/$topicName',
  getParentRoute: () => rootRouteImport,
} as any)
const S3BucketNameRoute = S3BucketNameRouteImport.update({
  id: '/s3/$bucketName',
  path: '/s3/$bucketName',
  getParentRoute: () => rootRouteImport,
} as any)
const DynamodbTableNameRoute = DynamodbTableNameRouteImport.update({
  id: '/dynamodb/$tableName',
  path: '/dynamodb/$tableName',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudfrontDistributionIdRoute =
  CloudfrontDistributionIdRouteImport.update({
    id: '/cloudfront/$distributionId',
    path: '/cloudfront/$distributionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CloudformationStackNameRoute = CloudformationStackNameRouteImport.update({
  id: '/cloudformation/$stackName',
  path: '/cloudformation/$stackName',
  getParentRoute: () => rootRouteImport,
} as any)
const IamUsersUserNameRoute = IamUsersUserNameRouteImport.update({
  id: '/iam/users/$userName',
  path: '/iam/users/$userName',
  getParentRoute: () => rootRouteImport,
} as any)
const IamPoliciesPolicyArnRoute = IamPoliciesPolicyArnRouteImport.update({
  id: '/iam/policies/$policyArn',
  path: '/iam/policies/$policyArn',
  getParentRoute: () => rootRouteImport,
} as any)
const IamGroupsGroupNameRoute = IamGroupsGroupNameRouteImport.update({
  id: '/iam/groups/$groupName',
  path: '/iam/groups/$groupName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cloudformation/$stackName': typeof CloudformationStackNameRoute
  '/cloudfront/$distributionId': typeof CloudfrontDistributionIdRoute
  '/dynamodb/$tableName': typeof DynamodbTableNameRoute
  '/s3/$bucketName': typeof S3BucketNameRoute
  '/sns/$topicName': typeof SnsTopicNameRoute
  '/sqs/$queueName': typeof SqsQueueNameRoute
  '/cloudformation/': typeof CloudformationIndexRoute
  '/cloudfront/': typeof CloudfrontIndexRoute
  '/dynamodb/': typeof DynamodbIndexRoute
  '/iam/': typeof IamIndexRoute
  '/s3/': typeof S3IndexRoute
  '/sns/': typeof SnsIndexRoute
  '/sqs/': typeof SqsIndexRoute
  '/iam/groups/$groupName': typeof IamGroupsGroupNameRoute
  '/iam/policies/$policyArn': typeof IamPoliciesPolicyArnRoute
  '/iam/users/$userName': typeof IamUsersUserNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cloudformation/$stackName': typeof CloudformationStackNameRoute
  '/cloudfront/$distributionId': typeof CloudfrontDistributionIdRoute
  '/dynamodb/$tableName': typeof DynamodbTableNameRoute
  '/s3/$bucketName': typeof S3BucketNameRoute
  '/sns/$topicName': typeof SnsTopicNameRoute
  '/sqs/$queueName': typeof SqsQueueNameRoute
  '/cloudformation': typeof CloudformationIndexRoute
  '/cloudfront': typeof CloudfrontIndexRoute
  '/dynamodb': typeof DynamodbIndexRoute
  '/iam': typeof IamIndexRoute
  '/s3': typeof S3IndexRoute
  '/sns': typeof SnsIndexRoute
  '/sqs': typeof SqsIndexRoute
  '/iam/groups/$groupName': typeof IamGroupsGroupNameRoute
  '/iam/policies/$policyArn': typeof IamPoliciesPolicyArnRoute
  '/iam/users/$userName': typeof IamUsersUserNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cloudformation/$stackName': typeof CloudformationStackNameRoute
  '/cloudfront/$distributionId': typeof CloudfrontDistributionIdRoute
  '/dynamodb/$tableName': typeof DynamodbTableNameRoute
  '/s3/$bucketName': typeof S3BucketNameRoute
  '/sns/$topicName': typeof SnsTopicNameRoute
  '/sqs/$queueName': typeof SqsQueueNameRoute
  '/cloudformation/': typeof CloudformationIndexRoute
  '/cloudfront/': typeof CloudfrontIndexRoute
  '/dynamodb/': typeof DynamodbIndexRoute
  '/iam/': typeof IamIndexRoute
  '/s3/': typeof S3IndexRoute
  '/sns/': typeof SnsIndexRoute
  '/sqs/': typeof SqsIndexRoute
  '/iam/groups/$groupName': typeof IamGroupsGroupNameRoute
  '/iam/policies/$policyArn': typeof IamPoliciesPolicyArnRoute
  '/iam/users/$userName': typeof IamUsersUserNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cloudformation/$stackName'
    | '/cloudfront/$distributionId'
    | '/dynamodb/$tableName'
    | '/s3/$bucketName'
    | '/sns/$topicName'
    | '/sqs/$queueName'
    | '/cloudformation/'
    | '/cloudfront/'
    | '/dynamodb/'
    | '/iam/'
    | '/s3/'
    | '/sns/'
    | '/sqs/'
    | '/iam/groups/$groupName'
    | '/iam/policies/$policyArn'
    | '/iam/users/$userName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cloudformation/$stackName'
    | '/cloudfront/$distributionId'
    | '/dynamodb/$tableName'
    | '/s3/$bucketName'
    | '/sns/$topicName'
    | '/sqs/$queueName'
    | '/cloudformation'
    | '/cloudfront'
    | '/dynamodb'
    | '/iam'
    | '/s3'
    | '/sns'
    | '/sqs'
    | '/iam/groups/$groupName'
    | '/iam/policies/$policyArn'
    | '/iam/users/$userName'
  id:
    | '__root__'
    | '/'
    | '/cloudformation/$stackName'
    | '/cloudfront/$distributionId'
    | '/dynamodb/$tableName'
    | '/s3/$bucketName'
    | '/sns/$topicName'
    | '/sqs/$queueName'
    | '/cloudformation/'
    | '/cloudfront/'
    | '/dynamodb/'
    | '/iam/'
    | '/s3/'
    | '/sns/'
    | '/sqs/'
    | '/iam/groups/$groupName'
    | '/iam/policies/$policyArn'
    | '/iam/users/$userName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CloudformationStackNameRoute: typeof CloudformationStackNameRoute
  CloudfrontDistributionIdRoute: typeof CloudfrontDistributionIdRoute
  DynamodbTableNameRoute: typeof DynamodbTableNameRoute
  S3BucketNameRoute: typeof S3BucketNameRoute
  SnsTopicNameRoute: typeof SnsTopicNameRoute
  SqsQueueNameRoute: typeof SqsQueueNameRoute
  CloudformationIndexRoute: typeof CloudformationIndexRoute
  CloudfrontIndexRoute: typeof CloudfrontIndexRoute
  DynamodbIndexRoute: typeof DynamodbIndexRoute
  IamIndexRoute: typeof IamIndexRoute
  S3IndexRoute: typeof S3IndexRoute
  SnsIndexRoute: typeof SnsIndexRoute
  SqsIndexRoute: typeof SqsIndexRoute
  IamGroupsGroupNameRoute: typeof IamGroupsGroupNameRoute
  IamPoliciesPolicyArnRoute: typeof IamPoliciesPolicyArnRoute
  IamUsersUserNameRoute: typeof IamUsersUserNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sqs/': {
      id: '/sqs/'
      path: '/sqs'
      fullPath: '/sqs/'
      preLoaderRoute: typeof SqsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sns/': {
      id: '/sns/'
      path: '/sns'
      fullPath: '/sns/'
      preLoaderRoute: typeof SnsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s3/': {
      id: '/s3/'
      path: '/s3'
      fullPath: '/s3/'
      preLoaderRoute: typeof S3IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iam/': {
      id: '/iam/'
      path: '/iam'
      fullPath: '/iam/'
      preLoaderRoute: typeof IamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dynamodb/': {
      id: '/dynamodb/'
      path: '/dynamodb'
      fullPath: '/dynamodb/'
      preLoaderRoute: typeof DynamodbIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloudfront/': {
      id: '/cloudfront/'
      path: '/cloudfront'
      fullPath: '/cloudfront/'
      preLoaderRoute: typeof CloudfrontIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloudformation/': {
      id: '/cloudformation/'
      path: '/cloudformation'
      fullPath: '/cloudformation/'
      preLoaderRoute: typeof CloudformationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sqs/$queueName': {
      id: '/sqs/$queueName'
      path: '/sqs/$queueName'
      fullPath: '/sqs/$queueName'
      preLoaderRoute: typeof SqsQueueNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sns/$topicName': {
      id: '/sns/$topicName'
      path: '/sns/$topicName'
      fullPath: '/sns/$topicName'
      preLoaderRoute: typeof SnsTopicNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s3/$bucketName': {
      id: '/s3/$bucketName'
      path: '/s3/$bucketName'
      fullPath: '/s3/$bucketName'
      preLoaderRoute: typeof S3BucketNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dynamodb/$tableName': {
      id: '/dynamodb/$tableName'
      path: '/dynamodb/$tableName'
      fullPath: '/dynamodb/$tableName'
      preLoaderRoute: typeof DynamodbTableNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloudfront/$distributionId': {
      id: '/cloudfront/$distributionId'
      path: '/cloudfront/$distributionId'
      fullPath: '/cloudfront/$distributionId'
      preLoaderRoute: typeof CloudfrontDistributionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloudformation/$stackName': {
      id: '/cloudformation/$stackName'
      path: '/cloudformation/$stackName'
      fullPath: '/cloudformation/$stackName'
      preLoaderRoute: typeof CloudformationStackNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iam/users/$userName': {
      id: '/iam/users/$userName'
      path: '/iam/users/$userName'
      fullPath: '/iam/users/$userName'
      preLoaderRoute: typeof IamUsersUserNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iam/policies/$policyArn': {
      id: '/iam/policies/$policyArn'
      path: '/iam/policies/$policyArn'
      fullPath: '/iam/policies/$policyArn'
      preLoaderRoute: typeof IamPoliciesPolicyArnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iam/groups/$groupName': {
      id: '/iam/groups/$groupName'
      path: '/iam/groups/$groupName'
      fullPath: '/iam/groups/$groupName'
      preLoaderRoute: typeof IamGroupsGroupNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CloudformationStackNameRoute: CloudformationStackNameRoute,
  CloudfrontDistributionIdRoute: CloudfrontDistributionIdRoute,
  DynamodbTableNameRoute: DynamodbTableNameRoute,
  S3BucketNameRoute: S3BucketNameRoute,
  SnsTopicNameRoute: SnsTopicNameRoute,
  SqsQueueNameRoute: SqsQueueNameRoute,
  CloudformationIndexRoute: CloudformationIndexRoute,
  CloudfrontIndexRoute: CloudfrontIndexRoute,
  DynamodbIndexRoute: DynamodbIndexRoute,
  IamIndexRoute: IamIndexRoute,
  S3IndexRoute: S3IndexRoute,
  SnsIndexRoute: SnsIndexRoute,
  SqsIndexRoute: SqsIndexRoute,
  IamGroupsGroupNameRoute: IamGroupsGroupNameRoute,
  IamPoliciesPolicyArnRoute: IamPoliciesPolicyArnRoute,
  IamUsersUserNameRoute: IamUsersUserNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
